trigger:
-main 

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release

- script: dotnet build --configuration ($buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

